apiVersion: v1
name: k8s-auto-updater
version: 0.1.0

description: "auto-update your cluster: sync your docker images and restart pods running on outdated images"
keywords:
  - cluster
  - update
  - images
  - pods
home: https://github.com/arnehilmann/k8s-auto-updater
sources:
  - https://github.com/arnehilmann/k8s-auto-updater
maintainers:
  - name: arnehilmann
    email: arne.hilmann@gmail.com
