apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: auto-updater-cronjob
  name: auto-updater-cronjob
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: auto-updater-job
        spec:

          serviceAccountName: auto-updater

          containers:
              #- image: alpine
          - image: arne/kubectldocker
            name: auto-updater
            imagePullPolicy: Always

            # command: ["/bin/sh", "-c", 'apk add curl docker jq && curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod a+rx ./kubectl && sync-images']
            command: ["/bin/sh", "-c", 'sync-pods']

            volumeMounts:
              - name: docker
                mountPath: /var/run/docker.sock
                readOnly: true

              - name: scripts
                mountPath: /usr/local/bin/sync-images
                subPath: sync-images

              - name: scripts
                mountPath: /usr/local/bin/sync-pods
                subPath: sync-pods

          volumes:
          - name: docker
            hostPath:
              path: /var/run/docker.sock

          - name: scripts
            configMap:
              name: auto-updater-scripts
              defaultMode: 0744

          restartPolicy: Never
      backoffLimit: 1
      # activeDeadlineSeconds: 300
