apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: auto-updater-cronjob
  name: auto-updater-cronjob
spec:
  schedule: {{ .Values.schedule | quote }}
  suspend: {{ .Values.suspend }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: auto-updater-job
            auto-update: never
        spec:

          serviceAccountName: auto-updater

          containers:
          - image: arne/kubectlskopeo
            name: auto-updater
            imagePullPolicy: Always

            command: [{{ .Values.command | quote }}]

            env:
              - name: POD_SELECTOR
                value: {{ .Values.podSelector | quote }}
              - name: IMAGE_REGEXP
                value: {{ .Values.imageRegExp | quote }}
              - name: NR_PODS_TO_DELETE
                value: {{ .Values.nrPodsToDelete | quote }}

            volumeMounts:
              - name: scripts
                mountPath: /usr/local/bin/
              - name: package
                mountPath: /usr/lib/python3.6/site-packages/autoupdater

          volumes:
          - name: scripts
            configMap:
              name: auto-updater-scripts
              defaultMode: 0744
          - name: package
            configMap:
              name: auto-updater-package

          restartPolicy: Never
      backoffLimit: 1
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
