apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-updater

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: auto-updater
rules:
  - apiGroups: ['']
    resources:
      - pods
    verbs:
      - list
      - get
      - delete
  - apiGroups: ['']
    resources:
      - secrets
    verbs:
      - get

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auto-updater
subjects:
- kind: ServiceAccount
  name: auto-updater
roleRef:
  kind: Role
  name: auto-updater
