apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-updater

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: rolling-update
rules:
  - apiGroups: ['']
    resources:
      - pods
      - secrets
    verbs:
      - get
  - apiGroups: ['']
    resources:
      - pods
    verbs:
      - list
  - apiGroups: ['extensions']
    resources:
      - replicasets
      - deployments
    verbs:
      - get
  - apiGroups: ['extensions']
    resources:
      - deployments
    verbs:
      - patch

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: delete-pods
rules:
  - apiGroups: ['']
    resources:
      - pods
    verbs:
      - list
      - get
      - delete
  - apiGroups: ['']
    resources:
      - secrets
    verbs:
      - get

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auto-updater
subjects:
- kind: ServiceAccount
  name: auto-updater
roleRef:
  kind: Role
  name: {{ default .Values.command .Values.role }}
